version: '2.4'
services:
  
  clamav-app:
    image: ryanwclark/clamav:latest
    container_name: clamav-app
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - ZABBIX_HOSTNAME=clamav-app
      - DEFINITIONS_UPDATE_FREQUENCY=60
    networks:
      - services
    restart: always

networks:
  services:
    external: true

